### ISSUE TITLE
Featurerequest Dockerimage

### ISSUE THREAD

**Issue by JanoschDeurer** [postwoman-io/postwoman-proxy#1]
I would like to have a Dockerimage for the postwoman proxy. It would also be great to integrate it into the official docker-compose of postwoman.

I can also offer to implement it, just give me some input on how you would like it and what the best way is to bring this together with postwoman.

**Comment by handong0123** [comment]
I have the same needs，I want it to merge with the docker image of postwoman

**Comment by MarcelPa** [comment]
Hopefully this issue is not too stale to be worked on.
I added a very simple Dockerfile to my fork: https://github.com/MarcelPa/postwoman-proxy

**Comment by JanoschDeurer** [comment]
Your PR #15 looks good to me, we could consider to not run this as root.

**Comment by MarcelPa** [comment]
You got a point there. I did not think of it, as I run this using rootless podman.
Will check that ;-)

**Comment by MarcelPa** [comment]
Pushed a new version, running the server as a non-root user :-)

**Comment by liyasthomas** [comment]
Closed in #15
