### ISSUE TITLE
(Linux Build Untested) Build fails on Linux

### ISSUE THREAD

**Issue by AndrewBastin** [postwoman-io/postwoman-proxy#2]
Running `./build.sh linux` fails on Linux with the error
```
cp: cannot stat 'resources/linux': No such file or directory
```

Tested on Arch Linux.

**Comment by NBTX** [comment]
I have not had the time to set up a Linux machine to test the installation. I've fixed the problem you've experienced by ensuring an empty resources skeleton directory for Linux is created (https://github.com/postwoman-io/postwoman-proxy/tree/master/resources/linux) - the folder for Darwin kind of explains the purpose of these skeleton directories a bit more (https://github.com/postwoman-io/postwoman-proxy/tree/master/resources/darwin).

Whilst the build is untested, I see no reason for it not to work - even if it hasn't got the polish of a normal Linux application, so I would appreciate it if you could continue trying to build and I'll keep fixing any issues that you need me to fix.

**Comment by AndrewBastin** [comment]
Yup, verified it. It works.
