### ISSUE TITLE
go build server/server.go does not work

### ISSUE THREAD

**Issue by lynnchae** [postwoman-io/postwoman-proxy#3]
go build server/server.go does not work on linux server

**Comment by NBTX** [comment]
Odd... What errors are you getting?

**Comment by lynnchae** [comment]
it just hang up and nothing print in the console
![image](https://user-images.githubusercontent.com/9653540/71173663-453ca180-229e-11ea-8655-74b1c6f7cdfe.png)

**Comment by NBTX** [comment]
I've pushed up some changes to improve the build tooling - which may have fixed these issues anyhow.
Try pulling the changes and running `./build.sh linux server`.

**Comment by NBTX** [comment]
Closing under the assumption that the issue is now fixed. If anyone experiences this issue again, leave another comment and I'll reopen the issue.
